initial port to nbdev2

diff --git a/.github/workflows/nbdev.yml b/.github/workflows/nbdev.yml
--- a/.github/workflows/nbdev.yml
+++ b/.github/workflows/nbdev.yml
@@ -1,9 +1,17 @@
 
 name: nbdev CI
 on: [push, pull_request]
+description: 'Test with nbdev'
 
-env:
-  FXND_CACHE: ~/fastxtend_cache
+inputs:
+  pre:
+    description: 'Install prerelease nbdev/execnb from master?'
+    required: false
+    default: ''
+  version:
+    description: 'Version of python to use'
+    required: false
+    default: '3.7'
 
 jobs:
   build:
@@ -13,41 +21,51 @@ jobs:
     - name: Set up python
       uses: actions/setup-python@v4
       with:
-        python-version: 3.7
+        python-version: ${{ inputs.version }}
         architecture: 'x64'
   
     - name: Activate python cache
       uses: actions/cache@v3
+      env:
+        cache-name: pip-packages
       with:
         path: |
           ${{ env.pythonLocation }}
-          ${{ env.FXND_CACHE }}
+          ${{ env.pip-packages }}
         key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
 
     - name: Install the library
       run: |
         sudo apt-get install libsndfile1-dev
         pip install --upgrade pip
+        if [ $USE_PRE ]; then
+          pip install -U git+https://github.com/fastai/fastcore.git
+          pip install -U git+https://github.com/fastai/ghapi.git
+          pip install -U git+https://github.com/fastai/execnb.git
+          pip install -U git+https://github.com/fastai/nbdev.git
+        fi
         pip install -e .[dev]
 
-    - name: Read all notebooks
+    - name: Check that notebooks are clean
       run: |
-        nbdev_read_nbs
-
-    - name: Check if all notebooks are cleaned
-      run: |
-        echo "Check we are starting with clean git checkout"
-        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
-        echo "Trying to strip out notebooks"
-        nbdev_clean_nbs
-        echo "Check that strip out was unnecessary"
+        nbdev_clean
         git status -s # display the status to see which nbs need cleaning up
-        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks !!!Remember to run nbdev_install_git_hooks"; false; fi
+        if [[ `git status --porcelain -uno` ]]; then
+          git status -uno
+          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+          false
+        fi
 
-    - name: Check if there is no diff library/notebooks
+    - name: Check that notebooks and library are in sync
       run: |
-        if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
+        nbdev_export
+        if [[ `git status --porcelain -uno` ]]; then
+          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+          git status -uno
+          git diff
+          exit 1;
+        fi
 
     - name: Run tests
       run: |
-        nbdev_test_nbs
+        nbdev_test
