Port to nbdev v2
Port to nbdev v2

diff --git a/.github/workflows/nbdev.yml b/.github/workflows/nbdev.yml
--- a/.github/workflows/nbdev.yml
+++ b/.github/workflows/nbdev.yml
@@ -1,9 +1,5 @@
-
-name: nbdev CI
-on: [push, pull_request]
-
-env:
-  FXND_CACHE: ~/fastxtend_cache
+name: nbdev-ci
+on: [workflow_dispatch, push, pull_request]
 
 jobs:
   build:
@@ -13,15 +9,17 @@ jobs:
     - name: Set up python
       uses: actions/setup-python@v4
       with:
-        python-version: 3.7
+        python-version: '3.7'
         architecture: 'x64'
   
     - name: Activate python cache
       uses: actions/cache@v3
+      env:
+        cache-name: pip-packages
       with:
         path: |
           ${{ env.pythonLocation }}
-          ${{ env.FXND_CACHE }}
+          ${{ env.pip-packages }}
         key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
 
     - name: Install the library
@@ -30,24 +28,26 @@ jobs:
         pip install --upgrade pip
         pip install -e .[dev]
 
-    - name: Read all notebooks
+    - name: Check that notebooks are clean
       run: |
-        nbdev_read_nbs
-
-    - name: Check if all notebooks are cleaned
-      run: |
-        echo "Check we are starting with clean git checkout"
-        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
-        echo "Trying to strip out notebooks"
-        nbdev_clean_nbs
-        echo "Check that strip out was unnecessary"
+        nbdev_clean
         git status -s # display the status to see which nbs need cleaning up
-        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks !!!Remember to run nbdev_install_git_hooks"; false; fi
+        if [[ `git status --porcelain -uno` ]]; then
+          git status -uno
+          echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+          false
+        fi
 
-    - name: Check if there is no diff library/notebooks
+    - name: Check that notebooks and library are in sync
       run: |
-        if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
+        nbdev_export
+        if [[ `git status --porcelain -uno` ]]; then
+          echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+          git status -uno
+          git diff
+          exit 1;
+        fi
 
     - name: Run tests
       run: |
-        nbdev_test_nbs
+        nbdev_test
